# Generated by Django 5.0.4 on 2024-04-18 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_type',
            field=models.CharField(choices=[('hardback', 'Hardback'), ('paperback', 'Paperback'), ('special', 'Special')], max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='market.category'),
            preserve_default=False,
        ),
    ]
